In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("best_data1.csv")

In [3]:
df.head()

Unnamed: 0  Unnamed: 0.1  Age  Gender                         Stream  \
0           0             0   22    Male  Electronics And Communication   
1           1             1   21  Female               Computer Science   
2           2             2   22  Female         Information Technology   
3           3             3   21    Male         Information Technology   
4           4             4   22    Male                     Mechanical   

   Internships  CGPA  Hostel  HistoryOfBacklogs  PlacedOrNot  Codechef  \
0            1     8       1                  1            1       3.0   
1            0     7       1                  1            1       2.0   
2            1     6       0                  0            1       3.0   
3            0     8       0                  1            1       2.0   
4            0     8       1                  0            1       2.0   

    Salary    DSA  
0  50917.0  700.0  
1  32614.0  500.0  
2  30048.0  500.0  
3  44910.0  600.0  
4  43962.0  600.0

In [4]:
df.drop('Unnamed: 0',axis=1,inplace=True)
df.drop('Unnamed: 0.1',axis=1,inplace=True)

In [5]:
df.head()

Age  Gender                         Stream  Internships  CGPA  Hostel  \
0   22    Male  Electronics And Communication            1     8       1   
1   21  Female               Computer Science            0     7       1   
2   22  Female         Information Technology            1     6       0   
3   21    Male         Information Technology            0     8       0   
4   22    Male                     Mechanical            0     8       1   

   HistoryOfBacklogs  PlacedOrNot  Codechef   Salary    DSA  
0                  1            1       3.0  50917.0  700.0  
1                  1            1       2.0  32614.0  500.0  
2                  0            1       3.0  30048.0  500.0  
3                  1            1       2.0  44910.0  600.0  
4                  0            1       2.0  43962.0  600.0

In [6]:
df.shape

(2966, 11)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2966 entries, 0 to 2965
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Age                2966 non-null   int64  
 1   Gender             2966 non-null   object 
 2   Stream             2966 non-null   object 
 3   Internships        2966 non-null   int64  
 4   CGPA               2966 non-null   int64  
 5   Hostel             2966 non-null   int64  
 6   HistoryOfBacklogs  2966 non-null   int64  
 7   PlacedOrNot        2966 non-null   int64  
 8   Codechef           2966 non-null   float64
 9   Salary             2966 non-null   float64
 10  DSA                2966 non-null   float64
dtypes: float64(3), int64(6), object(2)
memory usage: 255.0+ KB


In [8]:
df['Age'].unique()

array([22, 21, 23, 24, 28, 30, 25, 26, 20, 19, 29], dtype=int64)

In [9]:
df.head()

Age  Gender                         Stream  Internships  CGPA  Hostel  \
0   22    Male  Electronics And Communication            1     8       1   
1   21  Female               Computer Science            0     7       1   
2   22  Female         Information Technology            1     6       0   
3   21    Male         Information Technology            0     8       0   
4   22    Male                     Mechanical            0     8       1   

   HistoryOfBacklogs  PlacedOrNot  Codechef   Salary    DSA  
0                  1            1       3.0  50917.0  700.0  
1                  1            1       2.0  32614.0  500.0  
2                  0            1       3.0  30048.0  500.0  
3                  1            1       2.0  44910.0  600.0  
4                  0            1       2.0  43962.0  600.0

In [10]:
# Importing LabelEncoder from Sklearn
# library from preprocessing Module.
from sklearn.preprocessing import LabelEncoder
 
# Creating a instance of label Encoder.
le = LabelEncoder()
 
# Using .fit_transform function to fit label
# encoder and return encoded label
label = le.fit_transform(df['Gender'])
 
# printing label
df['Gender']=label

In [11]:
# Importing LabelEncoder from Sklearn
# library from preprocessing Module.
from sklearn.preprocessing import LabelEncoder
 
# Creating a instance of label Encoder.
pe = LabelEncoder()
 
# Using .fit_transform function to fit label
# encoder and return encoded label
laabel = pe.fit_transform(df['Stream'])
 
# printing label
df['Stream']=laabel

In [12]:
df.head()

Age  Gender  Stream  Internships  CGPA  Hostel  HistoryOfBacklogs  \
0   22       1       3            1     8       1                  1   
1   21       0       1            0     7       1                  1   
2   22       0       4            1     6       0                  0   
3   21       1       4            0     8       0                  1   
4   22       1       5            0     8       1                  0   

   PlacedOrNot  Codechef   Salary    DSA  
0            1       3.0  50917.0  700.0  
1            1       2.0  32614.0  500.0  
2            1       3.0  30048.0  500.0  
3            1       2.0  44910.0  600.0  
4            1       2.0  43962.0  600.0

In [13]:
df.isnull().sum()

Age                  0
Gender               0
Stream               0
Internships          0
CGPA                 0
Hostel               0
HistoryOfBacklogs    0
PlacedOrNot          0
Codechef             0
Salary               0
DSA                  0
dtype: int64

In [14]:
df.drop("PlacedOrNot",inplace=True,axis=1)


In [15]:
df.isnull().sum()

Age                  0
Gender               0
Stream               0
Internships          0
CGPA                 0
Hostel               0
HistoryOfBacklogs    0
Codechef             0
Salary               0
DSA                  0
dtype: int64

In [16]:
x=df.drop(columns='Salary')
y=df['Salary']

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [18]:
x_train.head()

Age  Gender  Stream  Internships  CGPA  Hostel  HistoryOfBacklogs  \
1484   22       0       0            1     8       0                  1   
944    22       1       1            1     8       0                  0   
2849   23       1       3            1     8       1                  1   
2575   20       0       4            1     8       1                  0   
2357   21       1       1            1     6       0                  0   

      Codechef    DSA  
1484       3.0  700.0  
944        3.0  700.0  
2849       3.0  700.0  
2575       3.0  700.0  
2357       3.0  500.0

In [19]:
print(x_train.size)
print(x_test.size)

21348
5346


In [20]:
from sklearn.preprocessing import StandardScaler

In [21]:
scaler= StandardScaler()
scaler.fit(x_train)

StandardScaler()

In [22]:
scaled_x=scaler.transform(x)

In [23]:
x_scale_train,x_scale_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [24]:
# ohe=OneHotEncoder()
# ohe.fit(x[['Internships','CGPA','DSA','codechef']])

In [25]:
lin_model = LinearRegression()
lin_model.fit(x_train,y_train)

LinearRegression()

In [26]:
from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor(n_neighbors=3)
knn.fit(x_train,y_train)

KNeighborsRegressor(n_neighbors=3)

In [27]:
pred = knn.predict(x_test)

In [28]:
print("MSE:",mean_squared_error(y_test,pred))
print("MAE:",mean_absolute_error(y_test,pred))
print("RMSE:",np.sqrt(mean_squared_error(y_test,pred)))

NameError: name 'mean_squared_error' is not defined

In [29]:
prediction = lin_model.predict(x_test)

In [30]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

In [31]:
print("MSE:",mean_squared_error(y_test,prediction))
print("MAE:",mean_absolute_error(y_test,prediction))
print("RMSE:",np.sqrt(mean_squared_error(y_test,prediction)))

MSE: 148484278.66733783
MAE: 9651.495139406425
RMSE: 12185.412535787938


In [32]:
r2_score(y_test,pred)

-0.3302413619308895

In [33]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)   
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape )
lm = LinearRegression()
scores = cross_val_score(lm, X_train, y_train, cv = 5)    
predictions = cross_val_predict(lm, X_test, y_test, cv = 5)
lm.fit(X_train, y_train)
y_hat = lm.predict(X_test)
lm.score(X_test, y_test)

(2076, 9) (2076,)
(890, 9) (890,)


0.9849992265931754

In [34]:
accuracy

NameError: name 'accuracy' is not defined

In [35]:
lm.predict([x.loc[99]])

c:\users\230405\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([32435.14008276])

In [36]:
x_scale_test.head()

Age  Gender  Stream  Internships  CGPA  Hostel  HistoryOfBacklogs  \
162    22       1       1            1     5       0                  0   
482    21       0       1            0     8       1                  1   
1502   22       1       4            1     6       0                  0   
308    22       0       1            1     6       1                  0   
2886   21       1       3            0     8       0                  1   

      Codechef    DSA  
162        3.0  200.0  
482        2.0  600.0  
1502       3.0  500.0  
308        3.0  500.0  
2886       2.0  600.0

In [37]:
x_=pd.DataFrame({'Age':21,'Gender':1,'Stream':4,'Internships':1,'CGPA':8,'Hostel':1,'HistoryOfBacklogs':0,'Codechef':5,'DSA':700},index=[0])

In [38]:
lm.predict(x_)

array([52644.70029283])

In [48]:
r2_score(y_test,y_hat)

0.9843161906019724

In [40]:
[x.loc[987]]

[Unnamed: 0           987.0
 Unnamed: 0.1         987.0
 Age                   22.0
 Gender                 0.0
 Stream                 1.0
 Internships            1.0
 CGPA                   8.0
 Hostel                 1.0
 HistoryOfBacklogs      0.0
 Codechef               3.0
 DSA                  700.0
 Name: 987, dtype: float64]

In [38]:
print("MSE:",mean_squared_error(y_test,y_hat))
print("MAE:",mean_absolute_error(y_test,y_hat))
print("RMSE:",np.sqrt(mean_squared_error(y_test,y_hat)))

MSE: 2337004.431782751
MAE: 1297.7384167945
RMSE: 1528.7264084141252


In [41]:
x.head()

Unnamed: 0  Unnamed: 0.1  Age  Gender  Stream  Internships  CGPA  Hostel  \
0           0             0   22       1       3            1     8       1   
1           1             1   21       0       1            0     7       1   
2           2             2   22       0       4            1     6       0   
3           3             3   21       1       4            0     8       0   
4           4             4   22       1       5            0     8       1   

   HistoryOfBacklogs  Codechef    DSA  
0                  1       3.0  700.0  
1                  1       2.0  500.0  
2                  0       3.0  500.0  
3                  1       2.0  600.0  
4                  0       2.0  600.0

In [46]:
x['Codechef']<3

0       False
1        True
2       False
3        True
4        True
        ...  
2961     True
2962    False
2963    False
2964    False
2965     True
Name: Codechef, Length: 2966, dtype: bool